// <auto-generated />

/*
* -------------------------------------------------------------------
* Copyright 2011-2025 Branimir Karadzic. All rights reserved.
* License: https://github.com/bkaradzic/bgfx/blob/master/LICENSE
*
* This file is auto-generated through `bgfx/scripts/bindings-cs.lua`
* Regenerate via `make idl`
*
* NebulaDev / https://github.com/Nebula-Developer
* -------------------------------------------------------------------
*/

using System.Runtime.InteropServices;

namespace Emi.Graphics.BgfxCS;

public static partial class Bgfx {
	#if WINDOWS
		private const string DllName = "bgfx.dll";
	#elif LINUX
	   	private const string DllName = "libbgfx.so";
	#elif OSX
		private const string DllName = "libbgfx.dylib";
	#else
		#warning Unsupported platform, or platform environment not setup.
		#warning Defaulting to Linux shared library name (libbgfx.so).
		private const string DllName = "libbgfx.so";
	#endif
}
